name = "Simple Survival"
author = "Hanjou"
version = "26.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "746afeb7b0dcddc5bf9727997dab7892e5184b806dd8a3390bedd74c9b080a09"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
