name = "Simple Survival"
author = "MrEnton"
version = "0.9.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e875b196d4d2d23dfa4eab626b1f5e88935ca01c4b7ec62df0e58c4579bac987"

[versions]
fabric = "0.14.16"
minecraft = "1.19.2"
