name = "Simple Survival 1 . 20"
author = "Joulan"
version = "0.10.33"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1715418c557404ba3dff756c5c3eeeb6db162f4f3b8d8832b487b758dc8be74b"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
