name = "Simple Survival"
author = "MrEnton"
version = "0.9.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee86ef240c27144ff2be58940641d285c937f370b5ec3ca6cf3edfb0553d8ff2"

[versions]
fabric = "0.14.16"
minecraft = "1.19.2"
