name = "Simple Survival 1 . 20"
author = "Joulan"
version = "0.10.30"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01abe7afcc6f8aeec2c03630b985efe02506959b56d2de69fe554dceb3c786cc"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
