name = "Simple Survival"
author = "MrEnton"
version = "0.9.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bae0376b4921a2ed3a06e7dd6d3a0b2f0ea22592d04cd20fc3313f55e08b4a4"

[versions]
fabric = "0.14.16"
minecraft = "1.19.2"
