name = "Simple Survival"
author = "Hanjou"
version = "26.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27e705d214a001b07fd39f4d4901c65912d90b2de10d6aac5e329d6adf2edb77"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
