name = "Simple Survival"
author = "MrEnton"
version = "0.9.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39fb0a7a295695c6cb79ff7228e1e5871760c073c3c5a892d9c3758163f64b9f"

[versions]
fabric = "0.14.16"
minecraft = "1.19.2"
